add 予定工数入力no
pentagon-tokyo/ptg-quality pull request #53
Opened 2023-07-10 08:00 UTC by yamazakihd

resolved https://github.com/pentagon-tokyo/ptg-quality/issues/9

2023-07-10 08:21 UTC, ymmtshny commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +* プロジェクトの進捗管理、リソースの管理、予算管理、品質向上のために、工数入力をします。
@yamazakihd 
なぜ重要なのか、もう少し具体的に書いてほしいです🙋‍♂️
参考：https://docs.page/pentagon-tokyo/ptg-quality/4.%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC/%E5%AE%9F%E7%B8%BE%E5%B7%A5%E6%95%B0%E5%85%A5%E5%8A%9B

2023-07-10 09:10 UTC, yamazakihd commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +* プロジェクトの進捗管理、リソースの管理、予算管理、品質向上のために、工数入力をします。
@ymmtshny 
修正したので、レビューお願いします！
fe96e0e54fbe5efd068f5824c1669c684a7cd1a5

2023-07-11 00:03 UTC, nambaseiichi-pentagon reviewed
@yamazakihd 
作成ありがとうございます！
コメントしました 🤚

2023-07-11 00:03 UTC, nambaseiichi-pentagon commented on docs/2.チケット仕様確認/予定工数入力.mdx
冒頭はサイドメニューと一致するよう、`#予定工数入力` を追記してください！

2023-07-11 00:03 UTC, nambaseiichi-pentagon commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +# なぜ工数入力を行うのか？
ここh2(`##`)にするか、冒頭のセクション内で予定工数入力を行う必要性について説明する文章にしてください 🙋

2023-07-11 00:03 UTC, nambaseiichi-pentagon commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +PMと相談して、バッファを取るなどする。
「その他」の位置は一番下が適切かなと思います 😄

2023-07-11 00:03 UTC, nambaseiichi-pentagon commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +# 予定工数入力のやり方
h1は冒頭以外使わないでください！
ここはh2にしてください！ 👍

2023-07-11 00:03 UTC, nambaseiichi-pentagon commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +* 予定工数入力後、予定よりも大幅に遅れそうな時
「大幅に遅れそうな時」だと、「遅れそうな時には相談しない」と判断されてしまいそうですね 😅 
またPM想定より早くても、稼働に空きができるリスクがあるため、これも相談が必要だと思いました！

例）
* 予定工数が、PM想定と異なる時（前倒しでも後ろ倒しでも）

2023-07-11 01:08 UTC, yamazakihd commented on docs/2.チケット仕様確認/予定工数入力.mdx
修正しました！
15cee5195846d61b2108ef30e467eae0b071079b

2023-07-11 01:10 UTC, yamazakihd commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +# なぜ工数入力を行うのか？
修正しました！
15cee5195846d61b2108ef30e467eae0b071079b

2023-07-11 01:11 UTC, yamazakihd commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +PMと相談して、バッファを取るなどする。
@nambaseiichi-pentagon 
修正しました！
90d2bcc361b0a575edc9a69f1b3e10eab025e412

2023-07-11 01:12 UTC, yamazakihd commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +# 予定工数入力のやり方
@nambaseiichi-pentagon 
修正しました！
15cee5195846d61b2108ef30e467eae0b071079b

2023-07-11 01:13 UTC, yamazakihd commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +* 予定工数入力後、予定よりも大幅に遅れそうな時
@nambaseiichi-pentagon 
修正しました！
44e43929e75051d3f4bf76eabcd3978c171446f9

2023-07-11 01:30 UTC, nambaseiichi-pentagon approved these changes
@yamazakihd 
修正ありがとうございます！
LGTM 👍 

（approve2つ以上でマージOKです）

2023-07-11 09:32 UTC, ymmtshny requested changes
対応ありがとうございます！！！
細かいですが、５W１Hを意識して書くと、わかりやすくなると思います🙋‍♂️

2023-07-11 09:32 UTC, ymmtshny commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +* プロジェクトの進捗管理、リソースの管理、予算管理、品質向上のために、工数入力をします。
「誰がするのか」主語を明記してください🙏

2023-07-11 09:32 UTC, ymmtshny commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +* 品質向上：工数入力することによって、テストに費やすことのできる時間を把握することができ、適切なテスト計画を立てることができる。
主語を明記してください🙏

2023-07-11 09:32 UTC, ymmtshny commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +* 自身のスキルを考慮し予定工数入力する
どこに入力するのか明記お願いします！

2023-07-11 09:32 UTC, ymmtshny commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +* 両方に問題がある場合は、フロントエンドとバックエンドそれぞれに対し予定工数入力をする。
- フロントエンドとバックエンドは別々のチケットとして、わかれている前提でしょうか？

2023-07-12 01:27 UTC, yamazakihd commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +* 両方に問題がある場合は、フロントエンドとバックエンドそれぞれに対し予定工数入力をする。
@ymmtshny 
分かれていない前提です。
627d345b27b27d5d7dc6c9eb63cec720ecc2a793

2023-07-12 01:28 UTC, yamazakihd commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +* 自身のスキルを考慮し予定工数入力する
@ymmtshny 
修正しました！
3a9e3b6de86c4317c2201ec977399f846f84082c

2023-07-12 01:28 UTC, yamazakihd commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +* 品質向上：工数入力することによって、テストに費やすことのできる時間を把握することができ、適切なテスト計画を立てることができる。
@ymmtshny 
修正しました！
744f6ebb6b8d68081d05b026ace5ab6676e529c5

2023-07-12 01:29 UTC, yamazakihd commented on docs/2.チケット仕様確認/予定工数入力.mdx
> +* プロジェクトの進捗管理、リソースの管理、予算管理、品質向上のために、工数入力をします。
@ymmtshny 
修正しました！
744f6ebb6b8d68081d05b026ace5ab6676e529c5

2023-07-18 03:55 UTC, ymmtshny approved these changes

2023-07-18 03:55 UTC, ymmtshny commented
@yamazakihd 修正ありがとうございます！マージしちゃいますね！

2023-07-18 03:55 UTC, merged