期待値理解のたたき台作成
pentagon-tokyo/ptg-quality pull request #56
Opened 2023-07-11 02:52 UTC by ke158

resolved https://github.com/pentagon-tokyo/ptg-quality/issues/18

プレビュー [期待値理解]()

2023-07-11 06:26 UTC, nambaseiichi-pentagon reviewed
@ke158 
ありがとうございます！
冒頭で気になった点があったのでコメントしました〜 

ご確認ください 🙏

2023-07-11 06:26 UTC, nambaseiichi-pentagon commented on docs/4.レビュー/期待値理解.mdx
> +開発者が正しく仕様を理解し、それに基づいて開発を行うことを指します。
対応いただいているページは「レビュー時のレビュアーにおける期待値理解」という出発点になるかなと思います！

以下を加味して冒頭を再考いただければと思います 🙋 

レビュアーがレビューを行う際、実装の期待値としてのゴールが明確でないと、何を基準に評価をすれば良いのかがわからないため、それを防ぐ意味で期待値理解が重要です。

レビュアーは正しい期待値の理解に努め、期待値に不明点がある場合、その認識合わせを行う必要があります。

2023-07-11 08:35 UTC, ke158 commented on docs/4.レビュー/期待値理解.mdx
> +開発者が正しく仕様を理解し、それに基づいて開発を行うことを指します。
参考にして修正いたしました🙋

2023-07-11 09:18 UTC, ymmtshny requested changes
対応ありがとうございます！！

そもそも「期待値とは？」という説明があるとわかりやすいかなと思いました🙋‍♂️

2023-07-11 23:20 UTC, ke158 commented
@ymmtshny 
期待値とは？を追加して編集いたします🙋

2023-07-14 01:01 UTC, nambaseiichi-pentagon approved these changes

2023-07-14 02:42 UTC, ymmtshny approved these changes
ご対応ありがとうございます！

2023-07-14 03:05 UTC, ke158 commented
マージいたします🙋

2023-07-14 04:06 UTC, merged