issue28 バグ共有
pentagon-tokyo/ptg-quality pull request #60
Opened 2023-07-13 00:36 UTC by sunachun

2023-07-13 01:01 UTC, sunachun commented
プレビューがいつもpage not foundなってしまう😅

2023-07-13 01:12 UTC, nambaseiichi-pentagon commented
大丈夫だと思います 😄 

[プレビュー](https://docs.page/pentagon-tokyo/ptg-quality~issue28/5.%E3%83%86%E3%82%B9%E3%83%88/%E3%83%90%E3%82%B0%E5%85%B1%E6%9C%89)

ブランチをPUSHした時点で以下のURLに品質ガイドラインプレビューが作成されるので、その後サイドメニューから作成したページに遷移するのが間違いないかと思います ✌️ 

`https://docs.page/pentagon-tokyo/ptg-qualityptg-quality{~ブランチ名}`

2023-07-13 01:21 UTC, nambaseiichi-pentagon reviewed
@sunachun 
ありがとうございます！
コメントしました〜 🙋

2023-07-13 01:21 UTC, nambaseiichi-pentagon commented on docs/5.テスト/バグ共有.mdx
> +自社内で iOS の TestFlight または Android の APK ファイルにてバグの発生を確認した場合、
プロジェクトによっては、iOS/Androidに限らず、管理画面、メール通知、その他いろんな成果物にバグが発生する可能性があるため、そのあたりもカバーできるといいかもしれないですね 🤔

2023-07-13 01:21 UTC, nambaseiichi-pentagon commented on docs/5.テスト/バグ共有.mdx
> +8. エビデンス動画(どのような動作を行うとバグが発生しているかを画面録画し、共有する)
動画がとれないケースなどものあるので、「スクショ＋再現手順」の方が好ましいときもありそうです 😄

2023-07-13 01:21 UTC, nambaseiichi-pentagon commented on docs/5.テスト/バグ共有.mdx
> +7. エビデンス動画
ここも同様で、動画がとれない（とりづらい）ケースもあるかなと思います！

2023-07-13 01:21 UTC, nambaseiichi-pentagon commented on docs/5.テスト/バグ共有.mdx
> +そして、いただいた内容をお客様から報告されたもの(お客様と連絡をとっている方)がバグ報告をするようにしましょう。
お客様がバグ報告をしているので、以下のようなパターンかなと思います！

* 報告を受けた人がバグ登録する
* お客様自身がバグ登録する

2023-07-13 01:21 UTC, nambaseiichi-pentagon commented on docs/5.テスト/バグ共有.mdx
> +その上で上記の 1~11 以外の項目である
「上記の 1~11」が紐づかないので、名称で指した方がいいかもしれないです！

2023-07-14 01:20 UTC, nambaseiichi-pentagon approved these changes
@sunachun 
LGTM 👍

2023-07-14 04:11 UTC, ymmtshny requested changes
ご対応ありがとうございます！
初見の人がわかりやすいドキュメントに仕上げましょう！

2023-07-14 04:11 UTC, ymmtshny commented on docs/5.テスト/バグ共有.mdx
> +バグを確認した方が以下の項目を下記 URL に記載し、エンジニア PM に mattermost で報告します。
下記 URLが離れすぎていて、分かりづらいので、
「後述するバグ共有のシートに記載し、」とするとわかりやすくなるかもです！

2023-07-14 04:11 UTC, ymmtshny commented on docs/5.テスト/バグ共有.mdx
> +1. お客様に直接 URL に記載していただく
下記 URLが離れすぎていて、分かりづらいので、
「後述するバグ共有のシートに記載し、」とするとわかりやすくなるかもです！

2023-07-14 04:11 UTC, ymmtshny commented on docs/5.テスト/バグ共有.mdx
> +詳細 URL: https://docs.google.com/spreadsheets/d/1eUnFwq19Nc_ycrztxW53boS2ti01NEMf-Q2EcoF2Z70/edit#gid=0
「バグ共有シート」とかで、名前つけましょうか！

2023-07-14 04:11 UTC, ymmtshny commented on docs/5.テスト/バグ共有.mdx
> +詳細 URL: https://docs.google.com/spreadsheets/d/1eUnFwq19Nc_ycrztxW53boS2ti01NEMf-Q2EcoF2Z70/edit#gid=1754347061
「バグ共有シート」とかで、名前つけましょうか！

2023-07-18 03:52 UTC, ymmtshny approved these changes

2023-07-18 03:53 UTC, merged